config/routes.rb
Rails.application.routes.draw do
  get '/blogs/countries' => 'blogs#countries'
  resources :blogs do
    resources :comments, except: [:index, :show]
  end

  post ':blog_id/comments' => 'comments#create'
  get 'comments/new' => 'comments#new'
  get '/blogs/:blog_id/comments/' => 'comments#show'
  get 'index' => 'blogs#index'
  post 'create' => 'blogs#create'
  get 'new' => 'blogs#new'
  get 'edit' => 'blogs#edit'
  get '/blogs/:id' => 'blogs#show'
  root :to => 'blogs#index'


  # get 'index' => 'blogs#index'
  # post 'create' => 'blogs#create'
  # get 'new' => 'blogs#new'
  # get '/blogs/:id' => 'blogs#show'
  # post ':blog_id/comments' => 'comments#create'
  # get 'comments/new' => 'comments#new'
  # get 'edit' => 'blogs#edit'
  # get '/blogs/:blog_id/comments/:id' => 'comments#show'


end
  #devise_for :users
  #root to: "blog#index"
#   resources :blogs do
#     resources :comments
#   end
#end



# Rails.application.routes.draw do
#   get 'comment/new'
#
#   get 'comment/edit'
#
#   get 'blog/index'
#
#   get 'blog/show'
#
#   get 'blog/edit'
#
#   get 'blog/create'
#
#
#
#   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound, with: :couldnt_find_record
  rescue_from NoMethodError, with: :no_method_error

  private
  def couldnt_find_record
    redirect_to root_url, notice: "That record doesn't exist!"
  end

  def no_method_error
    redirect_to root_url, notice: "The developer working on this didn't cover their butt appropriately. Our bad."
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
    @blogs = Blog.new
    @comment = Comment.new
  end

  def show
    @blog = Blog.find(params[:id])
    @comment = Comment.all
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
  if @blog.update(book_params)
    redirect_to(@blog)
  else
    render :edit
  end
end

  def create
    @blog = Blog.create!(user_name: params[:blog][:user_name], title: params[:blog][:title], date_traveled: params[:blog][:date_traveled], country: params[:blog][:country], city: params[:blog][:city], place: params[:blog][:place], article: params[:blog][:article], photo_url: params[:blog][:photo_url])
    redirect_to "/blogs/#{@blog.id}"

  end
  

  def countries
    @blogs = Blog.all
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
    redirect_to blogs_path
  end

  def edit
    @comment - Comment.find(params[:id])
  end

  def show
    @comment = Comment.find_by_id(@blog)
  end

  def create
    @comment = Comment.create(name: params[:comment][:name], user_comments: params[:comment][:user_comments])
    redirect_to blog_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/blogs/country.html.erb
<h1>Blog#countries</h1>
<p>Find me in app/views/blog/countries.html.erb</p>

<h1>Destinations</h1>

<p><%= <a href="/blogs/<%= blog.id %>">
  <%= blog.country %></a> %></p>

app/views/blogs/create.html.erb
<h1>Blog#create</h1>
<p>Find me in app/views/blog/create.html.erb</p>

app/views/blogs/edit.html.erb
<h1>Blog#edit</h1>

<%= form_for :blog do |f| %>
  Name: <%= f.text_field :user_name %><br />
  Title : <%= f.text_field :title %><br />
  Country : <%= f.text_field :country %><br />
  City : <%= f.text_field :city %><br />
  Place : <%= f.text_field :place %><br />
  Article : <%= f.text_area :article %><br />
  Photo_url : <%= f.text_field :photo_url %><br />
  Date Traveled : <%= f.text_field :date_traveled %><br />
  Admin?    : <%= f.check_box :admin %><br />
  <%= f.submit %>
<% end %>

app/views/blogs/index.html.erb
<div class="index-box">
  <h1>Articles</h1>

  <ul>
    <% @blogs.each do |blog| %>
      <li class="name"><a href="/blogs/<%= blog.id %>">
        <%= blog.user_name %></a></li>
      <li class="title"><%= blog.title %></li>
      <li class="date"><%= blog.date_traveled %></li>
      <li class="article"><%= blog.article %></li>

  <% end %>
</ul>
</div>

app/views/blogs/new.html.erb
<h2>Create A Blog</h2>

<%= form_for @blogs do |f| %>
  <%= f.label :user_name, class: "form_label" %>
  <%= f.text_field :user_name %>

  <%= f.label :title, class: "form_label" %>
  <%= f.text_field :title %>

  <%= f.label :date_traveled, class: "form_label" %>
  <%= f.text_field :date_traveled %>

  <%= f.label :country, class: "form_label" %>
  <%= f.text_field :country %>

  <%= f.label :city, class: "form_label" %>
  <%= f.text_field :city %>

  <%= f.label :place, class: "form_label"%>
  <%= f.text_field :place %>

  <%= f.label :article, class: "form_label" %>
  <%= f.text_field :article %>

  <%= f.label :photo_url, class: "form_label" %>
  <%= f.text_field :photo_url %>

  <%= f.submit "Create", class: "form_label" %>
<% end %>

app/views/blogs/show.html.erb
<h1><%=@blog.user_name%></h1>

<ul>
    <li> <%= @blog.user_name %></li>
    <li class="date"> <%= @blog.date_traveled %></li>
    <li class="article"> <%= @blog.article %></li>
    <li><img class='blog-photo' src="<%= @blog.photo_url %>"></li>
</ul>

<div>
  <ul>
    <% @blog.comments.each do |comments| %>
    <li> <%= @blog.comments.name %></li>
    <li> <%= @blog.comments.user_comments %></li>
    <% end %>
  </ul>
  <p>
    <%= link_to "Click here to comment", comments_new_path%>
  </p>
</div>

app/views/comments/edit.html.erb
<h1>Comment#edit</h1>
<p>Find me in app/views/comment/edit.html.erb</p>

app/views/comments/new.html.erb
<h1>Comment#new</h1>
<p>Find me in app/views/comment/new.html.erb</p>

<%= form_for @comment do |f| %>
  <%= f.label :name, class: "form_label" %>
  <%= f.text_field :name %>

  <%= f.label :user_comment, class: "form_label" %>
  <%= f.text_field :user_comment %>

  <%= f.submit "Post Comment", class: "form_label" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Clicker+Script|Lobster|Lustria|Pacifico|Quicksand" rel="stylesheet">
  </head>

  <body>
    <div>
      <h1 class="layout">Travel Logs</h1>
    </div>
    <div class="nav">
      <ul class="navigation">
        <li><%= link_to "Home", blogs_path%></li>
        <li><%= link_to "Destinations", blogs_countries_path%>
        <li><%= link_to "Create New Blog", new_blog_path %></li>
      </ul>
    </div>
    <%= yield %>
  </body>
</html>